---
title: Think Eva Report
email: contato@thinkeva.com.br
description: Think Eva Report
baseurl: ''
url: ''

social_icons:
 - title: facebook
   url: https://www.facebook.com/sharer/sharer.php?u=
 - title: twitter
   url: http://twitter.com/share?url=
 - title: linkedin
   url: https://www.linkedin.com/shareArticle?mini=true&title=Report%20Think%20Eva&summary=Summaryyyyy&url=
 - title: google-plus
   url: https://plus.google.com/share?url=


languages: ["pt-br", "en"]
exclude_from_localizations: ["javascript", "images", "css"]

markdown: kramdown
sass:
  sass_dir: "/assets/css"
  style: compressed
gems:
  - jekyll-seo-tag
  - jekyll-autoprefixer
  - jekyll-multiple-languages-plugin
exclude:
  - Gemfile
  - Gemfile.lock
